/**
 * Northline Build Co. design reminder: Forge & Form — lead with a dark site field, a human superintendent photo, field-report proof, and an offset project ledger.
 */
import { Link } from "wouter";
import { ArrowRight, ArrowUpRight, Check, ClipboardCheck, HardHat, ShieldCheck } from "lucide-react";
import { capabilities, projects, stats } from "../data";

const heroImage = "/manus-storage/northline-hero-site_3f15fb4b.jpg";

export default function Home() { return <>
  <section className="home-hero"><img src={heroImage} alt="Northline superintendent at an active commercial construction site"/><div className="hero-scrim"/><div className="container home-hero-content"><span className="section-code amber">NORTHLINE / BUILD CO.</span><h1>Built to<br/><em>hold its line.</em></h1><p>Complex construction, clearly led. Northline brings preconstruction, field execution, and accountable handoff under one disciplined team.</p><div className="hero-actions"><Link href="/quote" className="button button-amber">Start a project <ArrowUpRight size={18}/></Link><Link href="/projects" className="line-link">See our work <ArrowRight size={17}/></Link></div></div><div className="hero-site-card"><span>ACTIVE SITE / 14</span><strong>Clarity in the field.<br/>Control in the build.</strong><div><HardHat size={18}/><small>Commercial, residential<br/>& occupied-site work</small></div></div><div className="hero-bottom-rule"><span>SCROLL TO EXPLORE</span><i/><span>WEST COAST / SINCE 1999</span></div></section>
  <section className="stats-strip"><div className="container">{stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}<Link href="/about">Our field record <ArrowUpRight size={17}/></Link></div></section>
  <section className="intro-section"><div className="container intro-grid"><div><span className="section-code">WHAT WE BUILD / WHY IT HOLDS</span><h2>A better way to<br/>run the work.</h2></div><div className="intro-copy"><p>Northline is a construction partner for owners who expect their project to be built with sharp thinking, steady field leadership, and a real command of the details.</p><div className="check-rows"><span><Check size={17}/> Early facts, before assumptions.</span><span><Check size={17}/> A site team that stays accountable.</span><span><Check size={17}/> Decisions tracked to the work.</span></div><Link href="/about" className="line-link">Meet Northline <ArrowRight size={17}/></Link></div></div></section>
  <section className="capabilities-section"><div className="container"><div className="section-heading-dark"><span className="section-code amber">CAPABILITIES / 06</span><h2>Scope, aligned<br/>from day one.</h2><p>The right sequence, the right specialists, and a clear owner point of view through every phase.</p></div><div className="capability-list">{capabilities.map(item=>{const Icon=item.icon;return <Link href="/services" className="capability-row" key={item.title}><span>{item.code}</span><Icon size={28}/><h3>{item.title}</h3><p>{item.copy}</p><ArrowUpRight size={19}/></Link>})}</div></div></section>
  <section className="projects-section"><div className="container"><div className="projects-header"><div><span className="section-code">PROJECT LEDGER / SELECTED</span><h2>Work with<br/>a point of view.</h2></div><Link href="/projects" className="button button-outline">View all projects <ArrowUpRight size={18}/></Link></div><div className="project-ledger">{projects.map((project,index)=><Link href="/projects" className={`project-tile tile-${index+1}`} key={project.code}><img src={project.image} alt={project.title}/><div className="project-overlay"/><div className="project-meta"><span>{project.code}</span><span>{project.type}</span></div><div className="project-title"><h3>{project.title}</h3><p>{project.city}</p></div><span className="project-arrow"><ArrowUpRight size={18}/></span></Link>)}</div></div></section>
  <section className="process-band"><div className="container process-grid"><div><span className="section-code amber">HOW WE OPERATE</span><h2>Field-tested<br/>from the start.</h2></div><div className="process-steps"><article><span>01</span><h3>See the site</h3><p>We establish existing conditions, constraints, and the decisions that shape the work.</p></article><article><span>02</span><h3>Set the sequence</h3><p>Budget, schedule, procurement, and trade input align before construction pressure builds.</p></article><article><span>03</span><h3>Build with control</h3><p>Field reporting and practical leadership keep scope, quality, and handoff moving together.</p></article></div></div></section>
  <section className="home-contact"><div className="container"><div><ClipboardCheck size={31}/><span className="section-code">LOOKING AT A NEW SITE?</span><h2>Let’s map the<br/>next move.</h2></div><p>Send a short project brief, request a walk-through, or call us direct. We’ll start with the facts and build from there.</p><Link href="/quote" className="button button-dark">Request a quote <ArrowUpRight size={18}/></Link></div></section>
</>; }
