/**
 * Northline Build Co. design reminder: Forge & Form — capabilities are presented as an operational directory with a strong build-sequence signal.
 */
import { Link } from "wouter";
import { ArrowRight, ArrowUpRight, Check, ClipboardCheck } from "lucide-react";
import PageHero from "../components/PageHero";
import { capabilities } from "../data";

const craftImage = "/manus-storage/northline-craft-detail_fc295bf8.jpg";

export default function Services() { return <><PageHero section="Capabilities" title="The right way to build starts with the right path." copy="From the early work of defining a project to the field controls that carry it forward, Northline brings a connected construction approach."/><section className="services-directory"><div className="container"><div className="directory-head"><span className="section-code">SCOPE DIRECTORY / 06</span><p>Explore the expertise we bring to each construction phase. Every engagement is shaped around your site, constraints, and decision path.</p></div><div className="service-directory-list">{capabilities.map(item=>{const Icon=item.icon;return <article key={item.title}><span>{item.code}</span><Icon size={29}/><div><h2>{item.title}</h2><p>{item.copy}</p></div><Link href="/quote" aria-label={`Request a quote for ${item.title}`}><ArrowUpRight size={19}/></Link></article>})}</div></div></section><section className="precon-section"><div className="container precon-grid"><div className="precon-copy"><span className="section-code amber">PRECONSTRUCTION / IN PRACTICE</span><h2>Get the facts<br/>working early.</h2><p>Early construction involvement gives a project more room to make better choices. We help owners see the risk, organize the right inputs, and set a path before site pressure builds.</p><div className="precon-points"><span><Check size={17}/> Budget pathways and cost checkpoints</span><span><Check size={17}/> Procurement and long-lead planning</span><span><Check size={17}/> Constructability coordination</span></div><Link href="/quote" className="button button-amber">Talk preconstruction <ArrowRight size={18}/></Link></div><div className="precon-image"><div/><img src={craftImage} alt="Construction craft detail at a Northline work site"/><span><ClipboardCheck size={17}/> FIRST LOOK / FIELD FACTS</span></div></div></section></>; }
